# stage 1

FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json ./

RUN npm install --only=production

COPY . .

# stage 2


FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app .

EXPOSE 5000

CMD ["npm", "start"]

